import Foundation

enum Endpoints: String {
    case countries = "countries"
    case packages = "packages"
    case payments = "payments"
    case auth = "auth/token"
    case updateCustomer = "customer/edit"
    case esims = "customer/esims"
    case esimDetails = "customer/esims/placeholder/details"
    case signUpUser = "register"
    case forgotPassword = "forgot-password"
    case userLocation = "get_country"
    case search = "search"
    case customerOrders = "customer/orders"
    case customerPreferences = "customer/preferences"
    case changePassword = "customer/reset-password"
    case topUpEsim = "customer/esims/placeholder/top-up/packages"
    case promoCode = "customer/promotions/promo_code"
    case checkStock = "check-stock"
    case paymentsQuote = "payments/quote"
    case visaIframe = "customer/promotions/iframe"
    case validateVisa = "customer/promotions/validate"
    case storeReview = "reviews"
    case deleteAccount = "customer/delete"
    case updateEsim = "customer/esims/placeholder"
    case verifyEmail = "verify-email"
    case notificationSettings = "customer/notifications"
    case redeemVoucher = "customer/promotions/voucher"
    case loyaltyPoints = "customer/loyalty"
    case mokafaaOtpInitiate = "loyalty/mokafaa/otp/initiate"
    case mokafaaOtpValidate = "loyalty/mokafaa/otp/validate"
}
